version: '{branch}-$(APPVEYOR_REPO_COMMIT)'

environment:
  SOURCEMOD: 1.8
  
install:
  - ps: Invoke-WebRequest "https://www.sourcemod.net/latest.php?version=$env:SOURCEMOD&os=windows" -OutFile "sourcemod-$env:SOURCEMOD-windows.zip"
  - ps: Expand-Archive -Path "sourcemod-$env:SOURCEMOD-windows.zip" -DestinationPath "game"
  - ps: cd game\addons\sourcemod\scripting\include\
  - ps: Invoke-WebRequest "https://bitbucket.org/GoD_Tony/updater/raw/53ebb3e27e5a43bc46dc52dc0de76ac2fb48cd9e/include/updater.inc" -OutFile "updater.inc"
  - ps: cd ..

build: off

test_script:
  - cmd: spcomp sbpp_main.sp
  - cmd: spcomp sbpp_admcfg.sp
  - cmd: spcomp sbpp_comms.sp
  - cmd: spcomp sbpp_checker.sp
  - cmd: spcomp sbpp_sleuth.sp
  
after_test:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: 7z a sourcebans-pp.%APPVEYOR_REPO_BRANCH%-git%APPVEYOR_REPO_COMMIT%.zip %APPVEYOR_BUILD_FOLDER%\game\addons\sourcemod\scripting\compiled\*.smx
  
artifacts:
  - path: sourcebans-pp.$(APPVEYOR_REPO_BRANCH)-git$(APPVEYOR_REPO_COMMIT).zip
    name: sourcebans-pp